//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadMidasD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuento
    {
        public int idDescuento { get; set; }
        public Nullable<int> idFianza { get; set; }
        public Nullable<double> monto_Beneficiario { get; set; }
        public Nullable<double> t727 { get; set; }
        public Nullable<double> t727_Fianza_Real { get; set; }
        public Nullable<int> c21 { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<bool> validado { get; set; }
        public string validado_Por { get; set; }
        public string observacion { get; set; }
        public string usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<bool> registroActivo { get; set; }
    
        public virtual Fianza Fianza { get; set; }
    }
}
