//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadMidasD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscalaSalarial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EscalaSalarial()
        {
            this.Cargo = new HashSet<Cargo>();
        }
    
        public int idEscalaSalarial { get; set; }
        public string categoria { get; set; }
        public Nullable<int> clase { get; set; }
        public Nullable<int> nivel_Salarial { get; set; }
        public string denominacion_Puesto { get; set; }
        public Nullable<int> numero_Items { get; set; }
        public Nullable<int> idSueldoMensual { get; set; }
        public string usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<bool> registroActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargo> Cargo { get; set; }
        public virtual SueldoMensual SueldoMensual { get; set; }
    }
}
