//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadMidasD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fianza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fianza()
        {
            this.Descuento = new HashSet<Descuento>();
        }
    
        public int idFianza { get; set; }
        public Nullable<double> Nro_Fianza { get; set; }
        public Nullable<double> Nro_Fianza_Fianza_Real { get; set; }
        public Nullable<int> idTipoFianza { get; set; }
        public Nullable<int> idFuncionario { get; set; }
        public string registro_Sigma { get; set; }
        public Nullable<System.DateTime> fecha_Limite_Fianza { get; set; }
        public string resolucion_Administrativa { get; set; }
        public string comprobante_CPBTE { get; set; }
        public string descripcion_Tipo_Fianza_Real { get; set; }
        public string ubicacion_Fianza_Real { get; set; }
        public string folio_Fianza_Real { get; set; }
        public string concepto_Fianza_Real { get; set; }
        public string a_Favor_Fianza_Real { get; set; }
        public Nullable<double> ultimo_Registro_Fianza_Real { get; set; }
        public string tipo_Fianza_Real { get; set; }
        public string a_Favor_2_Fianza_Real { get; set; }
        public string estado_Bien_Inmueble_Fianza_Real { get; set; }
        public Nullable<bool> fianza_Completa_Habilitado { get; set; }
        public string usuario_Completa_Habilitado { get; set; }
        public Nullable<System.DateTime> fecha_Completa_Habilitado { get; set; }
        public Nullable<bool> fianza_Validada_Contabilidad { get; set; }
        public string usuario_Validada_Contabilidad { get; set; }
        public Nullable<System.DateTime> fecha_Validada_Contabilidad { get; set; }
        public Nullable<bool> fianza_Devuelta_Contabilidad { get; set; }
        public string usuario_Devuelta_Contabilidad { get; set; }
        public Nullable<System.DateTime> fecha_Devuelta_Contabilidad { get; set; }
        public Nullable<bool> fianza_Impresa_RRHH { get; set; }
        public string usuario_Impresa_RRHH { get; set; }
        public Nullable<System.DateTime> fecha_Impresa_RRHH { get; set; }
        public string observacion { get; set; }
        public string usuario_RRHH { get; set; }
        public Nullable<System.DateTime> fecha_RRHH { get; set; }
        public string usuario_Resolucion { get; set; }
        public Nullable<System.DateTime> fecha_Resolucion { get; set; }
        public string usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<bool> registroActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Descuento> Descuento { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual TipoFianza TipoFianza { get; set; }
    }
}
