//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadMidasD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.Fianza = new HashSet<Fianza>();
        }
    
        public int idFuncionario { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string numero_Memorando { get; set; }
        public Nullable<int> tipo_Contrato_Item { get; set; }
        public string vigencia_Contrato { get; set; }
        public Nullable<int> idCargo { get; set; }
        public Nullable<int> idOficina { get; set; }
        public string codigo_Distrito { get; set; }
        public Nullable<System.DateTime> fecha_Memorando { get; set; }
        public string usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<bool> registroActivo { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fianza> Fianza { get; set; }
        public virtual Oficina Oficina { get; set; }
    }
}
