//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadMidasD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MidasDEntities : DbContext
    {
        public MidasDEntities()
            : base("name=MidasDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AltasBajas> AltasBajas { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<CargoOficina> CargoOficina { get; set; }
        public virtual DbSet<Descuento> Descuento { get; set; }
        public virtual DbSet<Devolucion> Devolucion { get; set; }
        public virtual DbSet<DireccionAdministrativa> DireccionAdministrativa { get; set; }
        public virtual DbSet<Encargados> Encargados { get; set; }
        public virtual DbSet<EscalaSalarial> EscalaSalarial { get; set; }
        public virtual DbSet<Fianza> Fianza { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Imagen> Imagen { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Oficina> Oficina { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Reclasificacion> Reclasificacion { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolMenu> RolMenu { get; set; }
        public virtual DbSet<RolUsuario> RolUsuario { get; set; }
        public virtual DbSet<Solicitudes> Solicitudes { get; set; }
        public virtual DbSet<SueldoMensual> SueldoMensual { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoFianza> TipoFianza { get; set; }
        public virtual DbSet<Transferencia> Transferencia { get; set; }
        public virtual DbSet<UnidadEjecutora> UnidadEjecutora { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<viMenu> viMenu { get; set; }
        public virtual DbSet<viPersonaListar> viPersonaListar { get; set; }
        public virtual DbSet<viRol> viRol { get; set; }
        public virtual DbSet<viRolMenu> viRolMenu { get; set; }
        public virtual DbSet<viRolUsuario> viRolUsuario { get; set; }
        public virtual DbSet<viRolUsuarioListar> viRolUsuarioListar { get; set; }
        public virtual DbSet<viUsuario> viUsuario { get; set; }
        public virtual DbSet<viUsuarioListarDatos> viUsuarioListarDatos { get; set; }
        public virtual DbSet<viUsuarioMenu> viUsuarioMenu { get; set; }
    
        [DbFunction("MidasDEntities", "fnSplitString")]
        public virtual IQueryable<fnSplitString_Result> fnSplitString(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("string", @string) :
                new ObjectParameter("string", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnSplitString_Result>("[MidasDEntities].[fnSplitString](@string, @delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<Contador_Impresion_Result> Contador_Impresion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Contador_Impresion_Result>("Contador_Impresion");
        }
    
        public virtual int paAuditoriaRUD(string tabla, string idTabla, string host, string mac, string aplicacion)
        {
            var tablaParameter = tabla != null ?
                new ObjectParameter("tabla", tabla) :
                new ObjectParameter("tabla", typeof(string));
    
            var idTablaParameter = idTabla != null ?
                new ObjectParameter("idTabla", idTabla) :
                new ObjectParameter("idTabla", typeof(string));
    
            var hostParameter = host != null ?
                new ObjectParameter("host", host) :
                new ObjectParameter("host", typeof(string));
    
            var macParameter = mac != null ?
                new ObjectParameter("mac", mac) :
                new ObjectParameter("mac", typeof(string));
    
            var aplicacionParameter = aplicacion != null ?
                new ObjectParameter("aplicacion", aplicacion) :
                new ObjectParameter("aplicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paAuditoriaRUD", tablaParameter, idTablaParameter, hostParameter, macParameter, aplicacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> paContarDevolucionesPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("paContarDevolucionesPendientes");
        }
    
        public virtual int paDescuentoEditarEliminarFisico(Nullable<int> idFianza, Nullable<int> mes, Nullable<int> anio)
        {
            var idFianzaParameter = idFianza.HasValue ?
                new ObjectParameter("idFianza", idFianza) :
                new ObjectParameter("idFianza", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paDescuentoEditarEliminarFisico", idFianzaParameter, mesParameter, anioParameter);
        }
    
        public virtual int paDescuentoEditarEliminarFisicoEditar(Nullable<int> idFianza)
        {
            var idFianzaParameter = idFianza.HasValue ?
                new ObjectParameter("idFianza", idFianza) :
                new ObjectParameter("idFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paDescuentoEditarEliminarFisicoEditar", idFianzaParameter);
        }
    
        public virtual ObjectResult<paEscalaSalarialGestion_Result> paEscalaSalarialGestion(Nullable<int> gestion)
        {
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paEscalaSalarialGestion_Result>("paEscalaSalarialGestion", gestionParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> paFechaActual()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("paFechaActual");
        }
    
        public virtual ObjectResult<paFianzasListarMesAnioContaVali_Result> paFianzasListarMesAnioContaVali(Nullable<int> idUnidadEjecutora, Nullable<int> anio, Nullable<int> tipoFianza)
        {
            var idUnidadEjecutoraParameter = idUnidadEjecutora.HasValue ?
                new ObjectParameter("idUnidadEjecutora", idUnidadEjecutora) :
                new ObjectParameter("idUnidadEjecutora", typeof(int));
    
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            var tipoFianzaParameter = tipoFianza.HasValue ?
                new ObjectParameter("tipoFianza", tipoFianza) :
                new ObjectParameter("tipoFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFianzasListarMesAnioContaVali_Result>("paFianzasListarMesAnioContaVali", idUnidadEjecutoraParameter, anioParameter, tipoFianzaParameter);
        }
    
        public virtual ObjectResult<paFianzasListarMesAnioDescuentos_Result> paFianzasListarMesAnioDescuentos(Nullable<int> idUnidadEjecutora, Nullable<int> anio, Nullable<int> tipoFianza)
        {
            var idUnidadEjecutoraParameter = idUnidadEjecutora.HasValue ?
                new ObjectParameter("idUnidadEjecutora", idUnidadEjecutora) :
                new ObjectParameter("idUnidadEjecutora", typeof(int));
    
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            var tipoFianzaParameter = tipoFianza.HasValue ?
                new ObjectParameter("tipoFianza", tipoFianza) :
                new ObjectParameter("tipoFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFianzasListarMesAnioDescuentos_Result>("paFianzasListarMesAnioDescuentos", idUnidadEjecutoraParameter, anioParameter, tipoFianzaParameter);
        }
    
        public virtual ObjectResult<paFianzasPorFuncionarioBuscar_Result> paFianzasPorFuncionarioBuscar(string letra)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFianzasPorFuncionarioBuscar_Result>("paFianzasPorFuncionarioBuscar", letraParameter);
        }
    
        public virtual ObjectResult<paFianzaVerificarEnCurso_Result> paFianzaVerificarEnCurso(Nullable<int> idFuncionario)
        {
            var idFuncionarioParameter = idFuncionario.HasValue ?
                new ObjectParameter("idFuncionario", idFuncionario) :
                new ObjectParameter("idFuncionario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFianzaVerificarEnCurso_Result>("paFianzaVerificarEnCurso", idFuncionarioParameter);
        }
    
        public virtual ObjectResult<paFuncionarioFianzaActualBuscar_Result> paFuncionarioFianzaActualBuscar(string letra, Nullable<int> idUnidadEjecurota, Nullable<int> idTipoFianza)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idUnidadEjecurotaParameter = idUnidadEjecurota.HasValue ?
                new ObjectParameter("idUnidadEjecurota", idUnidadEjecurota) :
                new ObjectParameter("idUnidadEjecurota", typeof(int));
    
            var idTipoFianzaParameter = idTipoFianza.HasValue ?
                new ObjectParameter("idTipoFianza", idTipoFianza) :
                new ObjectParameter("idTipoFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFuncionarioFianzaActualBuscar_Result>("paFuncionarioFianzaActualBuscar", letraParameter, idUnidadEjecurotaParameter, idTipoFianzaParameter);
        }
    
        public virtual ObjectResult<paFuncionarioFianzaActualBuscarBaja_Result> paFuncionarioFianzaActualBuscarBaja(string letra, Nullable<int> idUnidadEjecurota, Nullable<int> idTipoFianza)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idUnidadEjecurotaParameter = idUnidadEjecurota.HasValue ?
                new ObjectParameter("idUnidadEjecurota", idUnidadEjecurota) :
                new ObjectParameter("idUnidadEjecurota", typeof(int));
    
            var idTipoFianzaParameter = idTipoFianza.HasValue ?
                new ObjectParameter("idTipoFianza", idTipoFianza) :
                new ObjectParameter("idTipoFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFuncionarioFianzaActualBuscarBaja_Result>("paFuncionarioFianzaActualBuscarBaja", letraParameter, idUnidadEjecurotaParameter, idTipoFianzaParameter);
        }
    
        public virtual ObjectResult<paFuncionarioFianzaActualBuscarCartilla_Result> paFuncionarioFianzaActualBuscarCartilla(string letra, Nullable<int> idUnidadEjecurota, Nullable<int> idTipoFianza)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idUnidadEjecurotaParameter = idUnidadEjecurota.HasValue ?
                new ObjectParameter("idUnidadEjecurota", idUnidadEjecurota) :
                new ObjectParameter("idUnidadEjecurota", typeof(int));
    
            var idTipoFianzaParameter = idTipoFianza.HasValue ?
                new ObjectParameter("idTipoFianza", idTipoFianza) :
                new ObjectParameter("idTipoFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFuncionarioFianzaActualBuscarCartilla_Result>("paFuncionarioFianzaActualBuscarCartilla", letraParameter, idUnidadEjecurotaParameter, idTipoFianzaParameter);
        }
    
        public virtual ObjectResult<paFuncionarioFianzaActualBuscarContaVali_Result> paFuncionarioFianzaActualBuscarContaVali(string letra, Nullable<int> idUnidadEjecurota, Nullable<int> idTipoFianza, Nullable<int> mes, Nullable<int> anio)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idUnidadEjecurotaParameter = idUnidadEjecurota.HasValue ?
                new ObjectParameter("idUnidadEjecurota", idUnidadEjecurota) :
                new ObjectParameter("idUnidadEjecurota", typeof(int));
    
            var idTipoFianzaParameter = idTipoFianza.HasValue ?
                new ObjectParameter("idTipoFianza", idTipoFianza) :
                new ObjectParameter("idTipoFianza", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFuncionarioFianzaActualBuscarContaVali_Result>("paFuncionarioFianzaActualBuscarContaVali", letraParameter, idUnidadEjecurotaParameter, idTipoFianzaParameter, mesParameter, anioParameter);
        }
    
        public virtual ObjectResult<paFuncionarioFianzaActualBuscarGeneral_Result> paFuncionarioFianzaActualBuscarGeneral(string letra, Nullable<int> idTipoFianza1, Nullable<int> idTipoFianza2)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianza1Parameter = idTipoFianza1.HasValue ?
                new ObjectParameter("idTipoFianza1", idTipoFianza1) :
                new ObjectParameter("idTipoFianza1", typeof(int));
    
            var idTipoFianza2Parameter = idTipoFianza2.HasValue ?
                new ObjectParameter("idTipoFianza2", idTipoFianza2) :
                new ObjectParameter("idTipoFianza2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFuncionarioFianzaActualBuscarGeneral_Result>("paFuncionarioFianzaActualBuscarGeneral", letraParameter, idTipoFianza1Parameter, idTipoFianza2Parameter);
        }
    
        public virtual ObjectResult<paFuncionarioFianzaActualBuscarGeneralAdministrador_Result> paFuncionarioFianzaActualBuscarGeneralAdministrador(string letra, Nullable<int> idTipoFianza1, Nullable<int> idTipoFianza2)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianza1Parameter = idTipoFianza1.HasValue ?
                new ObjectParameter("idTipoFianza1", idTipoFianza1) :
                new ObjectParameter("idTipoFianza1", typeof(int));
    
            var idTipoFianza2Parameter = idTipoFianza2.HasValue ?
                new ObjectParameter("idTipoFianza2", idTipoFianza2) :
                new ObjectParameter("idTipoFianza2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFuncionarioFianzaActualBuscarGeneralAdministrador_Result>("paFuncionarioFianzaActualBuscarGeneralAdministrador", letraParameter, idTipoFianza1Parameter, idTipoFianza2Parameter);
        }
    
        public virtual ObjectResult<paFuncionarioFianzaActualBuscaridFianza_Result> paFuncionarioFianzaActualBuscaridFianza(Nullable<int> idUnidadEjecutora, Nullable<int> idFianza)
        {
            var idUnidadEjecutoraParameter = idUnidadEjecutora.HasValue ?
                new ObjectParameter("idUnidadEjecutora", idUnidadEjecutora) :
                new ObjectParameter("idUnidadEjecutora", typeof(int));
    
            var idFianzaParameter = idFianza.HasValue ?
                new ObjectParameter("idFianza", idFianza) :
                new ObjectParameter("idFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFuncionarioFianzaActualBuscaridFianza_Result>("paFuncionarioFianzaActualBuscaridFianza", idUnidadEjecutoraParameter, idFianzaParameter);
        }
    
        public virtual ObjectResult<paFuncionarioFianzaActualBuscarMesAnioEditar_Result> paFuncionarioFianzaActualBuscarMesAnioEditar(string letra, Nullable<int> idUnidadEjecurota, Nullable<int> idTipoFianza, Nullable<int> mes, Nullable<int> anio)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idUnidadEjecurotaParameter = idUnidadEjecurota.HasValue ?
                new ObjectParameter("idUnidadEjecurota", idUnidadEjecurota) :
                new ObjectParameter("idUnidadEjecurota", typeof(int));
    
            var idTipoFianzaParameter = idTipoFianza.HasValue ?
                new ObjectParameter("idTipoFianza", idTipoFianza) :
                new ObjectParameter("idTipoFianza", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFuncionarioFianzaActualBuscarMesAnioEditar_Result>("paFuncionarioFianzaActualBuscarMesAnioEditar", letraParameter, idUnidadEjecurotaParameter, idTipoFianzaParameter, mesParameter, anioParameter);
        }
    
        public virtual ObjectResult<paFuncionarioFianzaActualBuscarTipoFianza_Result> paFuncionarioFianzaActualBuscarTipoFianza(string letra, Nullable<int> idTipoFianza)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianzaParameter = idTipoFianza.HasValue ?
                new ObjectParameter("idTipoFianza", idTipoFianza) :
                new ObjectParameter("idTipoFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFuncionarioFianzaActualBuscarTipoFianza_Result>("paFuncionarioFianzaActualBuscarTipoFianza", letraParameter, idTipoFianzaParameter);
        }
    
        public virtual ObjectResult<paFuncionarioFianzaActualBuscarTipoFianzaTotalEstadoValidado_Result> paFuncionarioFianzaActualBuscarTipoFianzaTotalEstadoValidado(string letra, Nullable<int> idTipoFianza, Nullable<int> estadoValidado)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianzaParameter = idTipoFianza.HasValue ?
                new ObjectParameter("idTipoFianza", idTipoFianza) :
                new ObjectParameter("idTipoFianza", typeof(int));
    
            var estadoValidadoParameter = estadoValidado.HasValue ?
                new ObjectParameter("estadoValidado", estadoValidado) :
                new ObjectParameter("estadoValidado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFuncionarioFianzaActualBuscarTipoFianzaTotalEstadoValidado_Result>("paFuncionarioFianzaActualBuscarTipoFianzaTotalEstadoValidado", letraParameter, idTipoFianzaParameter, estadoValidadoParameter);
        }
    
        public virtual ObjectResult<paFuncionarioVerificaridFianzaCompleta_Result> paFuncionarioVerificaridFianzaCompleta(Nullable<int> idUnidadEjecutora, Nullable<int> idFianza)
        {
            var idUnidadEjecutoraParameter = idUnidadEjecutora.HasValue ?
                new ObjectParameter("idUnidadEjecutora", idUnidadEjecutora) :
                new ObjectParameter("idUnidadEjecutora", typeof(int));
    
            var idFianzaParameter = idFianza.HasValue ?
                new ObjectParameter("idFianza", idFianza) :
                new ObjectParameter("idFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paFuncionarioVerificaridFianzaCompleta_Result>("paFuncionarioVerificaridFianzaCompleta", idUnidadEjecutoraParameter, idFianzaParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> paGetFecha()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("paGetFecha");
        }
    
        public virtual ObjectResult<paListaCargoOficina_Result> paListaCargoOficina(Nullable<int> idOficina, Nullable<int> gestion)
        {
            var idOficinaParameter = idOficina.HasValue ?
                new ObjectParameter("idOficina", idOficina) :
                new ObjectParameter("idOficina", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListaCargoOficina_Result>("paListaCargoOficina", idOficinaParameter, gestionParameter);
        }
    
        public virtual ObjectResult<paListaCargoOficinaAdmin_Result> paListaCargoOficinaAdmin(Nullable<int> idOficina, Nullable<int> gestion)
        {
            var idOficinaParameter = idOficina.HasValue ?
                new ObjectParameter("idOficina", idOficina) :
                new ObjectParameter("idOficina", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListaCargoOficinaAdmin_Result>("paListaCargoOficinaAdmin", idOficinaParameter, gestionParameter);
        }
    
        public virtual ObjectResult<paListaOficinaUnidadEjecutora_Result> paListaOficinaUnidadEjecutora(Nullable<int> idUnidadEjecutora)
        {
            var idUnidadEjecutoraParameter = idUnidadEjecutora.HasValue ?
                new ObjectParameter("idUnidadEjecutora", idUnidadEjecutora) :
                new ObjectParameter("idUnidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListaOficinaUnidadEjecutora_Result>("paListaOficinaUnidadEjecutora", idUnidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paListarFianzasEconomicasReporteGlobal_Result> paListarFianzasEconomicasReporteGlobal(string letra, Nullable<int> idTipoFianza1, Nullable<int> idTipoFianza2, Nullable<int> mes, Nullable<int> gestion)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianza1Parameter = idTipoFianza1.HasValue ?
                new ObjectParameter("idTipoFianza1", idTipoFianza1) :
                new ObjectParameter("idTipoFianza1", typeof(int));
    
            var idTipoFianza2Parameter = idTipoFianza2.HasValue ?
                new ObjectParameter("idTipoFianza2", idTipoFianza2) :
                new ObjectParameter("idTipoFianza2", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFianzasEconomicasReporteGlobal_Result>("paListarFianzasEconomicasReporteGlobal", letraParameter, idTipoFianza1Parameter, idTipoFianza2Parameter, mesParameter, gestionParameter);
        }
    
        public virtual int paListarFianzasEconomicasReporteGlobalDevolver(string letra, Nullable<int> idTipoFianza1, Nullable<int> idTipoFianza2, Nullable<int> mes, Nullable<int> gestion)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianza1Parameter = idTipoFianza1.HasValue ?
                new ObjectParameter("idTipoFianza1", idTipoFianza1) :
                new ObjectParameter("idTipoFianza1", typeof(int));
    
            var idTipoFianza2Parameter = idTipoFianza2.HasValue ?
                new ObjectParameter("idTipoFianza2", idTipoFianza2) :
                new ObjectParameter("idTipoFianza2", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paListarFianzasEconomicasReporteGlobalDevolver", letraParameter, idTipoFianza1Parameter, idTipoFianza2Parameter, mesParameter, gestionParameter);
        }
    
        public virtual ObjectResult<paListarFianzasEconomicasReporteGlobalUnidadEjecutora_Result> paListarFianzasEconomicasReporteGlobalUnidadEjecutora(string letra, Nullable<int> idTipoFianza1, Nullable<int> idTipoFianza2, Nullable<int> mes, Nullable<int> gestion, Nullable<int> idUnidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianza1Parameter = idTipoFianza1.HasValue ?
                new ObjectParameter("idTipoFianza1", idTipoFianza1) :
                new ObjectParameter("idTipoFianza1", typeof(int));
    
            var idTipoFianza2Parameter = idTipoFianza2.HasValue ?
                new ObjectParameter("idTipoFianza2", idTipoFianza2) :
                new ObjectParameter("idTipoFianza2", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var idUnidadEjecutoraParameter = idUnidadEjecutora.HasValue ?
                new ObjectParameter("idUnidadEjecutora", idUnidadEjecutora) :
                new ObjectParameter("idUnidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFianzasEconomicasReporteGlobalUnidadEjecutora_Result>("paListarFianzasEconomicasReporteGlobalUnidadEjecutora", letraParameter, idTipoFianza1Parameter, idTipoFianza2Parameter, mesParameter, gestionParameter, idUnidadEjecutoraParameter);
        }
    
        public virtual int paListarFianzasEconomicasReporteGlobalUnidadEjecutoraDevolver(string letra, Nullable<int> idTipoFianza1, Nullable<int> idTipoFianza2, Nullable<int> mes, Nullable<int> gestion, Nullable<int> idUnidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianza1Parameter = idTipoFianza1.HasValue ?
                new ObjectParameter("idTipoFianza1", idTipoFianza1) :
                new ObjectParameter("idTipoFianza1", typeof(int));
    
            var idTipoFianza2Parameter = idTipoFianza2.HasValue ?
                new ObjectParameter("idTipoFianza2", idTipoFianza2) :
                new ObjectParameter("idTipoFianza2", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var idUnidadEjecutoraParameter = idUnidadEjecutora.HasValue ?
                new ObjectParameter("idUnidadEjecutora", idUnidadEjecutora) :
                new ObjectParameter("idUnidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paListarFianzasEconomicasReporteGlobalUnidadEjecutoraDevolver", letraParameter, idTipoFianza1Parameter, idTipoFianza2Parameter, mesParameter, gestionParameter, idUnidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paListarFianzasEconomicasReporteT727_Result> paListarFianzasEconomicasReporteT727(string letra, Nullable<int> idTipoFianza1, Nullable<int> idTipoFianza2, Nullable<int> mes, Nullable<int> gestion)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianza1Parameter = idTipoFianza1.HasValue ?
                new ObjectParameter("idTipoFianza1", idTipoFianza1) :
                new ObjectParameter("idTipoFianza1", typeof(int));
    
            var idTipoFianza2Parameter = idTipoFianza2.HasValue ?
                new ObjectParameter("idTipoFianza2", idTipoFianza2) :
                new ObjectParameter("idTipoFianza2", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFianzasEconomicasReporteT727_Result>("paListarFianzasEconomicasReporteT727", letraParameter, idTipoFianza1Parameter, idTipoFianza2Parameter, mesParameter, gestionParameter);
        }
    
        public virtual int paListarFianzasEconomicasReporteT727Devolver(string letra, Nullable<int> idTipoFianza1, Nullable<int> idTipoFianza2, Nullable<int> mes, Nullable<int> gestion)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianza1Parameter = idTipoFianza1.HasValue ?
                new ObjectParameter("idTipoFianza1", idTipoFianza1) :
                new ObjectParameter("idTipoFianza1", typeof(int));
    
            var idTipoFianza2Parameter = idTipoFianza2.HasValue ?
                new ObjectParameter("idTipoFianza2", idTipoFianza2) :
                new ObjectParameter("idTipoFianza2", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paListarFianzasEconomicasReporteT727Devolver", letraParameter, idTipoFianza1Parameter, idTipoFianza2Parameter, mesParameter, gestionParameter);
        }
    
        public virtual ObjectResult<paListarFianzasEconomicasVisualizar_Result> paListarFianzasEconomicasVisualizar(string letra, Nullable<int> idTipoFianza1, Nullable<int> idTipoFianza2, Nullable<int> mes, Nullable<int> gestion)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianza1Parameter = idTipoFianza1.HasValue ?
                new ObjectParameter("idTipoFianza1", idTipoFianza1) :
                new ObjectParameter("idTipoFianza1", typeof(int));
    
            var idTipoFianza2Parameter = idTipoFianza2.HasValue ?
                new ObjectParameter("idTipoFianza2", idTipoFianza2) :
                new ObjectParameter("idTipoFianza2", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFianzasEconomicasVisualizar_Result>("paListarFianzasEconomicasVisualizar", letraParameter, idTipoFianza1Parameter, idTipoFianza2Parameter, mesParameter, gestionParameter);
        }
    
        public virtual ObjectResult<paListarFianzasPersona_Result> paListarFianzasPersona(Nullable<int> numeroDocumento)
        {
            var numeroDocumentoParameter = numeroDocumento.HasValue ?
                new ObjectParameter("numeroDocumento", numeroDocumento) :
                new ObjectParameter("numeroDocumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFianzasPersona_Result>("paListarFianzasPersona", numeroDocumentoParameter);
        }
    
        public virtual ObjectResult<paListarFianzasRealesReporteGlobal_Result> paListarFianzasRealesReporteGlobal(string letra, Nullable<int> idTipoFianza1, Nullable<int> idTipoFianza2, Nullable<int> mes, Nullable<int> gestion)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianza1Parameter = idTipoFianza1.HasValue ?
                new ObjectParameter("idTipoFianza1", idTipoFianza1) :
                new ObjectParameter("idTipoFianza1", typeof(int));
    
            var idTipoFianza2Parameter = idTipoFianza2.HasValue ?
                new ObjectParameter("idTipoFianza2", idTipoFianza2) :
                new ObjectParameter("idTipoFianza2", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFianzasRealesReporteGlobal_Result>("paListarFianzasRealesReporteGlobal", letraParameter, idTipoFianza1Parameter, idTipoFianza2Parameter, mesParameter, gestionParameter);
        }
    
        public virtual int paListarFianzasRealesReporteGlobalDevolver(string letra, Nullable<int> idTipoFianza1, Nullable<int> idTipoFianza2, Nullable<int> mes, Nullable<int> gestion)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianza1Parameter = idTipoFianza1.HasValue ?
                new ObjectParameter("idTipoFianza1", idTipoFianza1) :
                new ObjectParameter("idTipoFianza1", typeof(int));
    
            var idTipoFianza2Parameter = idTipoFianza2.HasValue ?
                new ObjectParameter("idTipoFianza2", idTipoFianza2) :
                new ObjectParameter("idTipoFianza2", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paListarFianzasRealesReporteGlobalDevolver", letraParameter, idTipoFianza1Parameter, idTipoFianza2Parameter, mesParameter, gestionParameter);
        }
    
        public virtual ObjectResult<paListarFianzasReclasificacion_Result> paListarFianzasReclasificacion(string letra)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFianzasReclasificacion_Result>("paListarFianzasReclasificacion", letraParameter);
        }
    
        public virtual ObjectResult<paListarFianzasReclasificacionPendientes_Result> paListarFianzasReclasificacionPendientes(string letra)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFianzasReclasificacionPendientes_Result>("paListarFianzasReclasificacionPendientes", letraParameter);
        }
    
        public virtual ObjectResult<paListarFianzasReclasificacionReporte_Result> paListarFianzasReclasificacionReporte(Nullable<System.DateTime> fecha1, Nullable<System.DateTime> fecha2)
        {
            var fecha1Parameter = fecha1.HasValue ?
                new ObjectParameter("fecha1", fecha1) :
                new ObjectParameter("fecha1", typeof(System.DateTime));
    
            var fecha2Parameter = fecha2.HasValue ?
                new ObjectParameter("fecha2", fecha2) :
                new ObjectParameter("fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFianzasReclasificacionReporte_Result>("paListarFianzasReclasificacionReporte", fecha1Parameter, fecha2Parameter);
        }
    
        public virtual ObjectResult<paListarFianzasTipoFianzaGestionUnidadEjecutoraHabilitado_Result> paListarFianzasTipoFianzaGestionUnidadEjecutoraHabilitado(string letra, Nullable<int> idTipoFianza, Nullable<int> gestion, Nullable<int> unidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianzaParameter = idTipoFianza.HasValue ?
                new ObjectParameter("idTipoFianza", idTipoFianza) :
                new ObjectParameter("idTipoFianza", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var unidadEjecutoraParameter = unidadEjecutora.HasValue ?
                new ObjectParameter("unidadEjecutora", unidadEjecutora) :
                new ObjectParameter("unidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFianzasTipoFianzaGestionUnidadEjecutoraHabilitado_Result>("paListarFianzasTipoFianzaGestionUnidadEjecutoraHabilitado", letraParameter, idTipoFianzaParameter, gestionParameter, unidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paListarFuncionariosFianzaConResolucion_Result> paListarFuncionariosFianzaConResolucion(string letra, string usuario)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFuncionariosFianzaConResolucion_Result>("paListarFuncionariosFianzaConResolucion", letraParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<paListarFuncionariosFianzaConResolucionBienesGravados_Result> paListarFuncionariosFianzaConResolucionBienesGravados(string letra, string usuario)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFuncionariosFianzaConResolucionBienesGravados_Result>("paListarFuncionariosFianzaConResolucionBienesGravados", letraParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<paListarFuncionariosFianzaDevolucion_Result> paListarFuncionariosFianzaDevolucion(string letra)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFuncionariosFianzaDevolucion_Result>("paListarFuncionariosFianzaDevolucion", letraParameter);
        }
    
        public virtual ObjectResult<paListarFuncionariosFianzaDevolucionContabilidad_Result> paListarFuncionariosFianzaDevolucionContabilidad(string letra)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFuncionariosFianzaDevolucionContabilidad_Result>("paListarFuncionariosFianzaDevolucionContabilidad", letraParameter);
        }
    
        public virtual ObjectResult<paListarFuncionariosFianzaDevolucionContabilidadReporte_Result> paListarFuncionariosFianzaDevolucionContabilidadReporte(Nullable<System.DateTime> fecha1, Nullable<System.DateTime> fecha2)
        {
            var fecha1Parameter = fecha1.HasValue ?
                new ObjectParameter("fecha1", fecha1) :
                new ObjectParameter("fecha1", typeof(System.DateTime));
    
            var fecha2Parameter = fecha2.HasValue ?
                new ObjectParameter("fecha2", fecha2) :
                new ObjectParameter("fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFuncionariosFianzaDevolucionContabilidadReporte_Result>("paListarFuncionariosFianzaDevolucionContabilidadReporte", fecha1Parameter, fecha2Parameter);
        }
    
        public virtual ObjectResult<paListarFuncionariosFianzaRRHH_Result> paListarFuncionariosFianzaRRHH(string letra, string usuario)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFuncionariosFianzaRRHH_Result>("paListarFuncionariosFianzaRRHH", letraParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<paListarFuncionariosFianzaTranferencias_Result> paListarFuncionariosFianzaTranferencias(string letra)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFuncionariosFianzaTranferencias_Result>("paListarFuncionariosFianzaTranferencias", letraParameter);
        }
    
        public virtual ObjectResult<paListarFuncionariosFianzaTranferenciasReporte_Result> paListarFuncionariosFianzaTranferenciasReporte(Nullable<System.DateTime> fecha1, Nullable<System.DateTime> fecha2)
        {
            var fecha1Parameter = fecha1.HasValue ?
                new ObjectParameter("fecha1", fecha1) :
                new ObjectParameter("fecha1", typeof(System.DateTime));
    
            var fecha2Parameter = fecha2.HasValue ?
                new ObjectParameter("fecha2", fecha2) :
                new ObjectParameter("fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarFuncionariosFianzaTranferenciasReporte_Result>("paListarFuncionariosFianzaTranferenciasReporte", fecha1Parameter, fecha2Parameter);
        }
    
        public virtual ObjectResult<paListarSolicitudesFianza_Result> paListarSolicitudesFianza(string letra, string usuario)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarSolicitudesFianza_Result>("paListarSolicitudesFianza", letraParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<paListarSolicitudesFianzaDiasRestantes_Result> paListarSolicitudesFianzaDiasRestantes(string letra, Nullable<int> dia1, Nullable<int> dia2, string usuario)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var dia1Parameter = dia1.HasValue ?
                new ObjectParameter("dia1", dia1) :
                new ObjectParameter("dia1", typeof(int));
    
            var dia2Parameter = dia2.HasValue ?
                new ObjectParameter("dia2", dia2) :
                new ObjectParameter("dia2", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarSolicitudesFianzaDiasRestantes_Result>("paListarSolicitudesFianzaDiasRestantes", letraParameter, dia1Parameter, dia2Parameter, usuarioParameter);
        }
    
        public virtual ObjectResult<paListarSolicitudesFianzaDiasRestantesReporte_Result> paListarSolicitudesFianzaDiasRestantesReporte(string letra, Nullable<int> dia1, Nullable<int> dia2, string usuario)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var dia1Parameter = dia1.HasValue ?
                new ObjectParameter("dia1", dia1) :
                new ObjectParameter("dia1", typeof(int));
    
            var dia2Parameter = dia2.HasValue ?
                new ObjectParameter("dia2", dia2) :
                new ObjectParameter("dia2", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paListarSolicitudesFianzaDiasRestantesReporte_Result>("paListarSolicitudesFianzaDiasRestantesReporte", letraParameter, dia1Parameter, dia2Parameter, usuarioParameter);
        }
    
        public virtual ObjectResult<paMenuCargar_Result> paMenuCargar(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paMenuCargar_Result>("paMenuCargar", usuarioParameter);
        }
    
        public virtual ObjectResult<paOficinaBuscar_Result> paOficinaBuscar(string letra, Nullable<int> idUnidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idUnidadEjecutoraParameter = idUnidadEjecutora.HasValue ?
                new ObjectParameter("idUnidadEjecutora", idUnidadEjecutora) :
                new ObjectParameter("idUnidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paOficinaBuscar_Result>("paOficinaBuscar", letraParameter, idUnidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paOficinasListar_Result> paOficinasListar(string letra)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("letra", letra) :
                new ObjectParameter("letra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paOficinasListar_Result>("paOficinasListar", letraParameter);
        }
    
        public virtual ObjectResult<paPersonaBuscar_Result> paPersonaBuscar(string letra)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paPersonaBuscar_Result>("paPersonaBuscar", letraParameter);
        }
    
        public virtual ObjectResult<paReporteCartilla_Result> paReporteCartilla(Nullable<int> idFianza)
        {
            var idFianzaParameter = idFianza.HasValue ?
                new ObjectParameter("idFianza", idFianza) :
                new ObjectParameter("idFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteCartilla_Result>("paReporteCartilla", idFianzaParameter);
        }
    
        public virtual ObjectResult<paReporteCartillaHabilitadoEditar_Result> paReporteCartillaHabilitadoEditar(Nullable<int> idFianza)
        {
            var idFianzaParameter = idFianza.HasValue ?
                new ObjectParameter("idFianza", idFianza) :
                new ObjectParameter("idFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteCartillaHabilitadoEditar_Result>("paReporteCartillaHabilitadoEditar", idFianzaParameter);
        }
    
        public virtual ObjectResult<paReporteCartillaT727_Result> paReporteCartillaT727(Nullable<int> idFianza)
        {
            var idFianzaParameter = idFianza.HasValue ?
                new ObjectParameter("idFianza", idFianza) :
                new ObjectParameter("idFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteCartillaT727_Result>("paReporteCartillaT727", idFianzaParameter);
        }
    
        public virtual ObjectResult<paReporteFormularioA2_Result> paReporteFormularioA2(string letra, Nullable<int> idTipoFianza, Nullable<int> mes, Nullable<int> gestion, Nullable<int> unidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianzaParameter = idTipoFianza.HasValue ?
                new ObjectParameter("idTipoFianza", idTipoFianza) :
                new ObjectParameter("idTipoFianza", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var unidadEjecutoraParameter = unidadEjecutora.HasValue ?
                new ObjectParameter("unidadEjecutora", unidadEjecutora) :
                new ObjectParameter("unidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteFormularioA2_Result>("paReporteFormularioA2", letraParameter, idTipoFianzaParameter, mesParameter, gestionParameter, unidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paReporteFormularioA2Reconsulta_Result> paReporteFormularioA2Reconsulta(string letra, Nullable<int> idTipoFianza, Nullable<int> mes, Nullable<int> gestion, Nullable<int> unidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianzaParameter = idTipoFianza.HasValue ?
                new ObjectParameter("idTipoFianza", idTipoFianza) :
                new ObjectParameter("idTipoFianza", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var unidadEjecutoraParameter = unidadEjecutora.HasValue ?
                new ObjectParameter("unidadEjecutora", unidadEjecutora) :
                new ObjectParameter("unidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteFormularioA2Reconsulta_Result>("paReporteFormularioA2Reconsulta", letraParameter, idTipoFianzaParameter, mesParameter, gestionParameter, unidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paReporteFuncionarioCertificadoidFianza_Result> paReporteFuncionarioCertificadoidFianza(Nullable<int> idUnidadEjecutora, Nullable<int> idFianza)
        {
            var idUnidadEjecutoraParameter = idUnidadEjecutora.HasValue ?
                new ObjectParameter("idUnidadEjecutora", idUnidadEjecutora) :
                new ObjectParameter("idUnidadEjecutora", typeof(int));
    
            var idFianzaParameter = idFianza.HasValue ?
                new ObjectParameter("idFianza", idFianza) :
                new ObjectParameter("idFianza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteFuncionarioCertificadoidFianza_Result>("paReporteFuncionarioCertificadoidFianza", idUnidadEjecutoraParameter, idFianzaParameter);
        }
    
        public virtual ObjectResult<paReporteSolDevolucion_Result> paReporteSolDevolucion(Nullable<int> idSolicitud)
        {
            var idSolicitudParameter = idSolicitud.HasValue ?
                new ObjectParameter("idSolicitud", idSolicitud) :
                new ObjectParameter("idSolicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteSolDevolucion_Result>("paReporteSolDevolucion", idSolicitudParameter);
        }
    
        public virtual ObjectResult<paReporteSolDevolucionNoRequiere_Result> paReporteSolDevolucionNoRequiere(Nullable<int> idSolicitud)
        {
            var idSolicitudParameter = idSolicitud.HasValue ?
                new ObjectParameter("idSolicitud", idSolicitud) :
                new ObjectParameter("idSolicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteSolDevolucionNoRequiere_Result>("paReporteSolDevolucionNoRequiere", idSolicitudParameter);
        }
    
        public virtual ObjectResult<paReporteSolFianEconomica_Result> paReporteSolFianEconomica(Nullable<int> idSolicitud)
        {
            var idSolicitudParameter = idSolicitud.HasValue ?
                new ObjectParameter("idSolicitud", idSolicitud) :
                new ObjectParameter("idSolicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteSolFianEconomica_Result>("paReporteSolFianEconomica", idSolicitudParameter);
        }
    
        public virtual ObjectResult<paReporteSolFianEconomicaNoRequiereFianza_Result> paReporteSolFianEconomicaNoRequiereFianza(Nullable<int> idSolicitud)
        {
            var idSolicitudParameter = idSolicitud.HasValue ?
                new ObjectParameter("idSolicitud", idSolicitud) :
                new ObjectParameter("idSolicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteSolFianEconomicaNoRequiereFianza_Result>("paReporteSolFianEconomicaNoRequiereFianza", idSolicitudParameter);
        }
    
        public virtual ObjectResult<paReporteSolFianEconomicaTotal_Result> paReporteSolFianEconomicaTotal(Nullable<int> idSolicitud)
        {
            var idSolicitudParameter = idSolicitud.HasValue ?
                new ObjectParameter("idSolicitud", idSolicitud) :
                new ObjectParameter("idSolicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteSolFianEconomicaTotal_Result>("paReporteSolFianEconomicaTotal", idSolicitudParameter);
        }
    
        public virtual ObjectResult<paSueldosMensuales_Result> paSueldosMensuales(Nullable<int> anio)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paSueldosMensuales_Result>("paSueldosMensuales", anioParameter);
        }
    
        public virtual ObjectResult<paUsuarioBuscar_Result> paUsuarioBuscar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paUsuarioBuscar_Result>("paUsuarioBuscar", parametroParameter);
        }
    
        public virtual ObjectResult<paValidacionEstadoFianzaContabilidad_Result> paValidacionEstadoFianzaContabilidad(string letra, Nullable<int> gestion, Nullable<int> unidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var unidadEjecutoraParameter = unidadEjecutora.HasValue ?
                new ObjectParameter("unidadEjecutora", unidadEjecutora) :
                new ObjectParameter("unidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paValidacionEstadoFianzaContabilidad_Result>("paValidacionEstadoFianzaContabilidad", letraParameter, gestionParameter, unidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paValidacionEstadoFianzaHabilitado_Result> paValidacionEstadoFianzaHabilitado(string letra, Nullable<int> gestion, Nullable<int> unidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var unidadEjecutoraParameter = unidadEjecutora.HasValue ?
                new ObjectParameter("unidadEjecutora", unidadEjecutora) :
                new ObjectParameter("unidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paValidacionEstadoFianzaHabilitado_Result>("paValidacionEstadoFianzaHabilitado", letraParameter, gestionParameter, unidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paValidacionEstadoFianzaRRHH_Result> paValidacionEstadoFianzaRRHH(string letra, Nullable<int> gestion, Nullable<int> unidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var unidadEjecutoraParameter = unidadEjecutora.HasValue ?
                new ObjectParameter("unidadEjecutora", unidadEjecutora) :
                new ObjectParameter("unidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paValidacionEstadoFianzaRRHH_Result>("paValidacionEstadoFianzaRRHH", letraParameter, gestionParameter, unidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paValidacionParaCertificados_Result> paValidacionParaCertificados(string letra, Nullable<int> gestion, Nullable<int> unidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var unidadEjecutoraParameter = unidadEjecutora.HasValue ?
                new ObjectParameter("unidadEjecutora", unidadEjecutora) :
                new ObjectParameter("unidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paValidacionParaCertificados_Result>("paValidacionParaCertificados", letraParameter, gestionParameter, unidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paValidacionParaCertificadosContabilidad_Result> paValidacionParaCertificadosContabilidad(string letra, Nullable<int> gestion, Nullable<int> unidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var unidadEjecutoraParameter = unidadEjecutora.HasValue ?
                new ObjectParameter("unidadEjecutora", unidadEjecutora) :
                new ObjectParameter("unidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paValidacionParaCertificadosContabilidad_Result>("paValidacionParaCertificadosContabilidad", letraParameter, gestionParameter, unidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paValidacionParaCertificadosHabilitado_Result> paValidacionParaCertificadosHabilitado(string letra, Nullable<int> gestion, Nullable<int> unidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var unidadEjecutoraParameter = unidadEjecutora.HasValue ?
                new ObjectParameter("unidadEjecutora", unidadEjecutora) :
                new ObjectParameter("unidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paValidacionParaCertificadosHabilitado_Result>("paValidacionParaCertificadosHabilitado", letraParameter, gestionParameter, unidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paValidacionParaCertificadosRRHH_Result> paValidacionParaCertificadosRRHH(string letra, Nullable<int> idTipoFianza, Nullable<int> gestion, Nullable<int> unidadEjecutora)
        {
            var letraParameter = letra != null ?
                new ObjectParameter("Letra", letra) :
                new ObjectParameter("Letra", typeof(string));
    
            var idTipoFianzaParameter = idTipoFianza.HasValue ?
                new ObjectParameter("idTipoFianza", idTipoFianza) :
                new ObjectParameter("idTipoFianza", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            var unidadEjecutoraParameter = unidadEjecutora.HasValue ?
                new ObjectParameter("unidadEjecutora", unidadEjecutora) :
                new ObjectParameter("unidadEjecutora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paValidacionParaCertificadosRRHH_Result>("paValidacionParaCertificadosRRHH", letraParameter, idTipoFianzaParameter, gestionParameter, unidadEjecutoraParameter);
        }
    
        public virtual ObjectResult<paValidacionRegistroSolicitudes_Result> paValidacionRegistroSolicitudes(string nRODOCUMENTO)
        {
            var nRODOCUMENTOParameter = nRODOCUMENTO != null ?
                new ObjectParameter("NRODOCUMENTO", nRODOCUMENTO) :
                new ObjectParameter("NRODOCUMENTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paValidacionRegistroSolicitudes_Result>("paValidacionRegistroSolicitudes", nRODOCUMENTOParameter);
        }
    }
}
