//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadMidasD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oficina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oficina()
        {
            this.CargoOficina = new HashSet<CargoOficina>();
            this.Funcionario = new HashSet<Funcionario>();
        }
    
        public int idOficina { get; set; }
        public string oficina1 { get; set; }
        public string codigo_Distrito { get; set; }
        public string codigo_Zeus { get; set; }
        public Nullable<int> idZeus { get; set; }
        public Nullable<int> idUnidadEjecutora { get; set; }
        public Nullable<int> cuantia { get; set; }
        public Nullable<double> porcentaje_Descuento { get; set; }
        public string usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<bool> registroActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargoOficina> CargoOficina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionario> Funcionario { get; set; }
        public virtual UnidadEjecutora UnidadEjecutora { get; set; }
    }
}
