//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadMidasD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Encargados = new HashSet<Encargados>();
            this.Imagen = new HashSet<Imagen>();
        }
    
        public int idPersona { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public string numero_Documento { get; set; }
        public string pais_Nacimiento { get; set; }
        public string departamento_Nacimiento { get; set; }
        public string localidad_Nacimiento { get; set; }
        public string provincia_Nacimiento { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public string nombres { get; set; }
        public string domicilio { get; set; }
        public string profesion { get; set; }
        public string sexo { get; set; }
        public string estado_Civil { get; set; }
        public Nullable<System.DateTime> fecha_Nacimiento { get; set; }
        public string usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<bool> registroActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encargados> Encargados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagen> Imagen { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
