//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadMidasD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes
    {
        public int idSolicitud { get; set; }
        public string tipo_Solicitud_Fianza { get; set; }
        public string numero_memorando { get; set; }
        public Nullable<System.DateTime> fecha_Memorando { get; set; }
        public Nullable<int> numero_Fianza_Solicitud { get; set; }
        public Nullable<int> gestion { get; set; }
        public Nullable<System.DateTime> fecha_limite_presentacion { get; set; }
        public string usuario_RRHH { get; set; }
        public Nullable<System.DateTime> fecha_Registro_RRHH { get; set; }
        public string usuario_Asesor_Acepta { get; set; }
        public Nullable<bool> solicitud_Aceptada { get; set; }
        public System.DateTime fecha_Aceptacion { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<int> idCargo { get; set; }
        public Nullable<int> idOficina { get; set; }
        public Nullable<int> idEscalaSalarial { get; set; }
        public Nullable<int> idSueldoMensual { get; set; }
        public string tipo_Contrato_Item { get; set; }
        public string vigencia_Contrato { get; set; }
        public Nullable<int> idFianza_Transferir { get; set; }
        public Nullable<double> monto_Fianza_Transferir { get; set; }
        public Nullable<int> idFianza_Nueva { get; set; }
        public Nullable<int> idTipoFianza { get; set; }
        public Nullable<int> idDevolucion_Registro { get; set; }
        public Nullable<int> idTransferencia_Nueva { get; set; }
        public string observacion { get; set; }
        public string usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<bool> registroActivo { get; set; }
    
        public virtual Devolucion Devolucion { get; set; }
        public virtual Transferencia Transferencia { get; set; }
    }
}
