//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadMidasD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transferencia()
        {
            this.Solicitudes = new HashSet<Solicitudes>();
        }
    
        public int idTransferencia { get; set; }
        public Nullable<int> idFianza { get; set; }
        public Nullable<int> idFuncionario { get; set; }
        public Nullable<int> idCargoAnterior { get; set; }
        public string numero_Memorando_Anterior { get; set; }
        public Nullable<System.DateTime> fecha_Memorando_Anterior { get; set; }
        public string tipo_Contrato_item_Anterior { get; set; }
        public string vigencia_Contrato_Anterior { get; set; }
        public Nullable<int> idTipoFianzaAnterior { get; set; }
        public Nullable<int> idOficinaAnterior { get; set; }
        public Nullable<int> idSueldoSueldoMensual { get; set; }
        public string fecha_LimiteFianza_Anterior { get; set; }
        public string resolucion_Administrativa_Anterior { get; set; }
        public string usuario_RRHH_Anterior { get; set; }
        public string fecha_RRHH_Anterior { get; set; }
        public string usuario_Resolucion_Anterior { get; set; }
        public Nullable<System.DateTime> fecha_Resolucion_Anterior { get; set; }
        public string usuario_Impresa_Anterior { get; set; }
        public Nullable<System.DateTime> fecha_Impresa_Anterior { get; set; }
        public string observacion_Anterior { get; set; }
        public Nullable<double> monto_Fianza_Transferir { get; set; }
        public string resolucion_Administrativa_Transferencia { get; set; }
        public string usuario_Contabilidad_Transferencia { get; set; }
        public Nullable<System.DateTime> fecha_Contabilidad_Transferencia { get; set; }
        public Nullable<int> mes_Transferencia { get; set; }
        public Nullable<int> anio_Tranferencia { get; set; }
        public string observacion_Transferencia { get; set; }
        public string usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<bool> registroActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
    }
}
