//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadMidasD
{
    using System;
    using System.Collections.Generic;
    
    public partial class viPersonaListar
    {
        public int idPersona { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public string nombres { get; set; }
        public string nombre_Completo { get; set; }
        public string domicilio { get; set; }
        public string sexo { get; set; }
        public string estado_Civil { get; set; }
        public string tipo_documento { get; set; }
        public string numero_documento { get; set; }
        public Nullable<System.DateTime> fecha_Nacimiento { get; set; }
    }
}
